### ISSUE TITLE
False positive: Php 7.1 syntax

### ISSUE THREAD

**Issue by fooman** [magento/marketplace-eqp#104]
MEQP2.PHP.Syntax.PHPSyntax errors when using php 7.1 syntax on class constant visibility:
https://wiki.php.net/rfc/class_const_visibility / http://www.php.net/ChangeLog-7.php#7.1.0

The particular package is targeted at Magento 2.3 only which means only php 7.1 and 7.2 would be in the list of supported php versions.

**Comment by lenaorobei** [comment]
@fooman thank you for reporting this issue. We will think of how to revisit `PHPSyntax` sniff in order to check code syntax against appropriate PHP version.

**Comment by bididev** [comment]
Any update on selective rules? 

https://magento.stackexchange.com/questions/277725/extension-update-technical-submission-fails

**Comment by lenaorobei** [comment]
@Raven0us EQP CodeSniffer check will be switched to [magento/magento-coding-standard](https://github.com/magento/magento-coding-standard) soon. This issue is resolved there.

**Comment by lenaorobei** [comment]
Closing this issue because this repo now contains sniffs for Magento 1.x code only.
Please refer to [magento/magento-coding-standard](https://github.com/magento/magento-coding-standard) for Magento 2.x coding standard.

This rule was removed in [magento/magento-coding-standard](https://github.com/magento/magento-coding-standard) in order to eliminate false-positive findings.

Starting from 7/11 EQP CodeSniffer check uses [magento/magento-coding-standard](https://github.com/magento/magento-coding-standard).
