### ISSUE TITLE
False Positive : Possible slow SQL method

### ISSUE THREAD

**Issue by kanduvisla** [magento/marketplace-eqp#109]
I've got an install script that creates a CMS page like this:

    $page = $this->pageFactory->create();
    $page->setIsActive(true);
    $page->setTitle('Error');
    $page->setPageLayout('1column');
    $page->setContentHeading('Something went wrong');
    $page->setContent('<p>It looks like something went wrong while handling your request. More details:</p>');
    $page = $this->pageRepository->save($page);

This triggers the "Possible slow SQL method" sniff because the word "like" is in my query.

**Comment by lenaorobei** [comment]
@kanduvisla thanks for reporting. This is known issue and is one of the reason why we didn't include "Possible SQL" sniff to the consolidated [Magento Coding Standard](https://github.com/magento/magento-coding-standard).

**Comment by kanduvisla** [comment]
Hi @lenaorobei ,

I'm a bit confused now. Magento states that if you want to submit an extension to the marketplace, you have to conform to the MEQP2 standards. So what is this Magento Coding Standard? Is the Extension Quality Program to be deprecated?

**Comment by lenaorobei** [comment]
@kanduvisla [Magento Coding Standard](https://github.com/magento/magento-coding-standard) is an ongoing project of coding standards consolidation (Magento core and MEQP). 
For now Marketplace still uses MEQP. Once we make change we will notify developers about this.

**Comment by lenaorobei** [comment]
Closing this issue because this repo now contains sniffs for Magento 1.x code only.
Please refer to [magento/magento-coding-standard](https://github.com/magento/magento-coding-standard) for Magento 2.x coding standard.

This rule was removed in [magento/magento-coding-standard](https://github.com/magento/magento-coding-standard) in order to eliminate false-positive findings.

Starting from 7/11 Marketplace uses [magento/magento-coding-standard](https://github.com/magento/magento-coding-standard).
