### ISSUE TITLE
MEQP1.Performance.InefficientMethods : GetFirstItem always triggered

### ISSUE THREAD

**Issue by digitalpianism** [magento/marketplace-eqp#26]
This warning is getting trigerred even if you limit your collection for example with this code:

```
/** @var Mage_Cms_Model_Resource_Page_Collection $collection */
$collection = Mage::getResourceModel('cms/page_collection')
    ->addFieldToFilter('identifier', 'home')
    ->setPageSize(1)
    ->setCurPage(1);

if ($collection->getSize()) {
    /** @var Mage_Cms_Model_Page $page */
    $page = $collection->getFirstItem();
}
```

It should not trigger if `setPageSize()` is called on the collection IMHO

**Comment by ikruchynskyi** [comment]
@digitalpianism thanks for reporting. Unfortunately, such scans hard or even impossible to implement in the scope of static checks. Lots of our sniffs can be triggered on false-positive issues and that's why they are marked as warnings. Each warning has its own severity which indicates level of possible issue in PHPCS finding.

**Comment by digitalpianism** [comment]
@ikruchynskyi yeah I thought this would be hard too ^^ thanks for the heads up
