### ISSUE TITLE
Exception : MEQP1.Exceptions.Namespace does not exist

### ISSUE THREAD

**Issue by quienti** [magento/marketplace-eqp#31]
Version used: last (1.0.4)

![sans titre 2](https://cloud.githubusercontent.com/assets/7326954/21006726/851353c0-bd3a-11e6-9531-57a9f21026d9.jpg)

**Comment by lenaorobei** [comment]
@quienti could you please run `vendor/bin/phpcs -i` command and show the output?

**Comment by quienti** [comment]
Of course
`The installed coding standards are PSR2, PEAR, Squiz, PHPCS, MySource, PSR1 and Zend
`

**Comment by lenaorobei** [comment]
Thanks, I get the point. The problem is that post-install scripts in `composer.json` were added a few days ago and we haven't prepared new release yet. We will release the new version as soon as possible and will add it to [repo.magento.com](repo.magento.com).
For now to make it work you should run `vendor/bin/phpcs --config-set installed_paths ../../..`

**Comment by quienti** [comment]
It's works fine!
Thanks you
