### ISSUE TITLE
Throwing exception class from the same namespace is marked as error

### ISSUE THREAD

**Issue by LukeOl** [magento/marketplace-eqp#45]
This is related to throwing exceptions.
If in class, other class is used, but both classes belongs to the same namespace, EQP tool will result:
ERROR - Namespace for <<other class>> class is not specified.

Example:
Test.php
```
<?php

namespace Somespace;

class Test
{
    public function run()
    {
        throw new TestException('Test exception message');
    }
}
```

TestException.php
```
<?php

namespace Somespace;

class TestException extends \Exception
{
}
```
Result of testing file Test.php:
```
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 9 | ERROR | Namespace for TestException class is not specified.
----------------------------------------------------------------------
```

However, if you change run() method a bit:
```
public function run()
{
    $testException = new TestException('Test exception message');
}
```
Tools won't result an error.

I am attaching code, which is correct, but tools will result error:
[test.tar.gz](https://github.com/magento/marketplace-eqp/files/1006830/test.tar.gz)

**Comment by lenaorobei** [comment]
@LukeOl it's a known issue. 

PHP_CodeSniffes proceeds with [PHP tokens](http://php.net/manual/en/tokens.php). It runs through each file, gets all tokens and analyzes their position in the file. It cannot check something like `class_exists()` because it's not a dynamic check. If you add `use` statement, you will see no error, because [sniff analyses it](https://github.com/magento/marketplace-eqp/blob/master/MEQP1/Sniffs/Exceptions/NamespaceSniff.php#L61). 

And why the second code example throws no error? It's because [the sniff](https://github.com/magento/marketplace-eqp/blob/master/MEQP1/Sniffs/Exceptions/NamespaceSniff.php) observes only `T_CATCH` and `T_THROW ` tokens.

**Comment by oleksii-lisovyi** [comment]
+1

**Comment by lenaorobei** [comment]
Closing this issue because this repo now contains sniffs for Magento 1.x code only.
Please refer to [magento/magento-coding-standard](https://github.com/magento/magento-coding-standard) for Magento 2.x coding standard.

This rule was removed in [magento/magento-coding-standard](https://github.com/magento/magento-coding-standard) in order to eliminate false-positive findings.
