### ISSUE TITLE
Direct object instantiation for exceptions

### ISSUE THREAD

**Issue by bobbrodie** [magento/marketplace-eqp#47]
Extending the Magento APIs, we're running into this:

```
Direct object instantiation (class
Mage_Api2_Exception) is discouraged in Magento.
```

This is something used throughout the core, which also fails.

**Comment by lenaorobei** [comment]
@bobbrodie some of the sniffs provide false-positive findings. If you look [into the code](https://github.com/magento/marketplace-eqp/blob/master/MEQP1/Sniffs/Classes/ObjectInstantiationSniff.php#L43-L46), you can see, that `MEQP1.Classes. ObjectInstantiation` sniff detects all `new` keywords and following class names, which start with:
```
protected $disallowedClassPrefixes = [
    'Mage_',
    'Enterprise_',
];
```
That's why it is marked as a warning, not as an error. This is done to warn the developers and to draw their attention.

**Comment by bobbrodie** [comment]
I totally understand that, but if someone is using this in an automated system and does not want to ignore warnings or specific severities, then they run into trouble. This is one case where you can safely directly instantiate the object and it might be worthwhile to have a whitelist, to allow classes ending in _Exception.

**Comment by lenaorobei** [comment]
That's a good point, thanks. We will improve this sniff as soon as possible.
