### ISSUE TITLE
A false positive: «Only dependency assignment operations are allowed in constructor»

### ISSUE THREAD

**Issue by shochdoerfer** [magento/marketplace-eqp#77]
When running EQP against our [Force Login](https://github.com/bitExpert/magento2-force-login/) module the warning "Only dependency assignment operations are allowed in constructor. No other operations are allowed." shows up for this piece of code:
```php
/**
 * @param StrategyInterface[] $strategies
 */
public function __construct(array $strategies)
{
    foreach ($strategies as $identifier => $strategyEntry) {
        $this->strategies[$identifier] = $strategyEntry;
        $this->strategyNames[$identifier] = $strategyEntry->getName();
    }
}
```

I guess it might be quite hard to guess what constructor code is valid, but in that regard the warning does not make any sense to me.

**Comment by lenaorobei** [comment]
Closing this issue because this repo now contains sniffs for Magento 1.x code only.
Please refer to [magento/magento-coding-standard](https://github.com/magento/magento-coding-standard) for Magento 2.x coding standard.

This rule was removed in [magento/magento-coding-standard](https://github.com/magento/magento-coding-standard) in order to eliminate false-positive findings.
